apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: gitlab
  source:
    repoURL: https://github.com/pedromota533/kubernetes-intro
    targetRevision: HEAD
    path: k8s/kustomize/gitlab
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
