apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  description: GitLab self-hosted git server
  sourceRepos:
    - "*"
  destinations:
    - namespace: gitlab
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
