.PHONY: help

help:
	@printf "\n$(BOLD)Usage:$(NC)  make $(CYAN)<target>$(NC)\n\n"
	@printf "$(BOLD)k3s$(NC)\n"
	@printf "  $(CYAN)k3s-download$(NC)   Download k3s binary from GitHub  (K3S_RELEASE=$(K3S_RELEASE))\n"
	@printf "  $(CYAN)k3s-install$(NC)    Write systemd service and reload daemon\n"
	@printf "  $(CYAN)k3s-start$(NC)      Start the k3s systemd service\n"
	@printf "  $(CYAN)k3s-stop$(NC)       Stop the k3s systemd service\n"
	@printf "  $(CYAN)k3s-restart$(NC)    Restart the k3s systemd service\n"
	@printf "  $(CYAN)k3s-enable$(NC)     Enable k3s to start on boot\n"
	@printf "  $(CYAN)k3s-disable$(NC)    Disable k3s from starting on boot\n"
	@printf "  $(CYAN)k3s-status$(NC)     Show k3s service status\n"
	@printf "  $(CYAN)k3s-delete$(NC)     Stop, remove service file and binary\n"
	@printf "  $(CYAN)k3s-purge$(NC)      $(RED)Complete removal of k3s, config, and data$(NC)\n"
	@printf "\n$(BOLD)ArgoCD$(NC)\n"
	@printf "  $(CYAN)install$(NC)        Install ArgoCD into the cluster\n"
	@printf "  $(CYAN)uninstall$(NC)      Remove ArgoCD and all its Applications\n"
	@printf "  $(CYAN)link$(NC)           Apply root-app (link ArgoCD to this repo)\n"
	@printf "  $(CYAN)unlink$(NC)         Delete root-app (unlink ArgoCD from this repo)\n"
	@printf "  $(CYAN)install-argocd-bin$(NC)  Download ArgoCD CLI binary to ./bin/argocd\n"
	@printf "  $(CYAN)argocd-sync$(NC)    Sync a specific app  (APP=<app-name>)\n"
	@printf "  $(CYAN)port-forward$(NC)   Forward ArgoCD server to localhost:8080\n"
	@printf "  $(CYAN)password$(NC)       Print the ArgoCD initial admin password\n"
	@printf "  $(CYAN)status$(NC)         Show all resources in the $(NAMESPACE) namespace\n"
	@printf "  $(CYAN)pods$(NC)           Show pods across all namespaces\n"
	@printf "  $(CYAN)deploy-apps$(NC)    Apply kustomize app manifests\n"
	@printf "  $(CYAN)remove-apps$(NC)    Delete kustomize app manifests\n"
	@printf "  $(CYAN)nuke-apps$(NC)      Delete ALL ArgoCD Applications (cascade)\n"
	@printf "  $(CYAN)prune-apps$(NC)     Remove namespaces left behind after uninstall\n"
	@printf "  $(CYAN)ghcr-secret$(NC)    Add ghcr.io OCI credentials to ArgoCD  (GHCR_USER= GHCR_TOKEN=)\n"
	@printf "\n$(BOLD)Hosts$(NC)\n"
	@printf "  $(CYAN)hosts-add$(NC)      Add project domains to /etc/hosts  (NODE_IP=$(NODE_IP))\n"
	@printf "  $(CYAN)hosts-remove$(NC)   Remove project domains from /etc/hosts\n"
	@printf "\n"
